### ISSUE TITLE
Retrieving the COM class factory for component with CLSID failed

### ISSUE THREAD

**Issue by xcngl** [xWTF/SnipeIT-bPAC#1]
After clicking the "Click here to print" button, the prompt "{"code":500,"msg":"Unknown error occured: Retrieving the COM class factory for component with CLSID {B940C105-7F01-46FE-BF41-E040B9BDA83D} failed due to the following error: 80040154 \u6CA1\u6709\u6CE8\u518C\u7C7B (0x80040154 (REGDB_E_CLASSNOTREG))."}" will appear. What should I do？

**Comment by de-sec** [comment]
Try to use x86 Version of bPAC Client Components - fixed it for our use case (local usage on a Win11 Pro Workstation).

**Comment by xWTF** [comment]
If an x86 version of client component solves the issue, the binaries I compiled might be running under 32 bit mode for some reason.
That doesn't make any sense to me since I've specified `<PlatformTarget>x64</PlatformTarget>`...

Anyway, I have added a label indicating current cpu bit width in v1.0.2, feel free to check it out.

![image](https://github.com/xWTF/SnipeIT-bPAC/assets/31540475/50df2352-b653-4d8c-98b1-6ee3656ea2c2)

**Comment by xcngl** [comment]
![image](https://github.com/xWTF/SnipeIT-bPAC/assets/110588072/9f4a0fb4-be90-40a7-b5ae-2f7e5c451d30)

**Comment by xcngl** [comment]
这个怎么搞呢？点击按钮后提示{“code”:200}。看了下这个端口是监听状态，但是访问不了

**Comment by xWTF** [comment]
`{“code”:200}` = request success
the printer should be printing your labels atm

**Comment by xcngl** [comment]
没有打印任务，是必须用 Brother 标签打印机吗？

**Comment by xWTF** [comment]
> 没有打印任务，是必须用 Brother 标签打印机吗？

该项目使用 “bPAC SDK” 来执行打印任务。
b-PAC 是一个将数据发送到 **Brother 标签打印机/移动打印机** 的组件，因此该项目只能用于 Brother 标签打印机。

**Comment by xcngl** [comment]
好吧😂谢谢
